version: '3.8'

services:
  scraper-service:
    build: 
      context: .
      dockerfile: Dockerfile

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - '80:80'
    depends_on:
      - scraper-service